# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib RjaNLP
#' @importFrom Rcpp evalCpp
NULL

executeCabocha <- function(str) {
    .Call('RjaNLP_executeCabocha', PACKAGE = 'RjaNLP', str)
}

#' @useDynLib RjaNLP
#' @importFrom Rcpp evalCpp
NULL

executeMecab <- function(str) {
    .Call('RjaNLP_executeMecab', PACKAGE = 'RjaNLP', str)
}

